### ISSUE TITLE
sonar-measures-export fails if using --history and -b together

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1085]
Currently the branch history export is not implemented. Only the main branch.

So you cannot use -b and --history at the same time otherwise you may get:
```
sonar-measures-export  -f measures.csv -b --history
/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2024-05-30 14:18:53,309 | sonar-tools | INFO    | MainThread      | Set debug level to INFO
2024-05-30 14:18:53,310 | sonar-tools | INFO    | MainThread      | sonar-tools version 3.1
2024-05-30 14:18:53,472 | sonar-tools | INFO    | MainThread      | Listing projects
Traceback (most recent call last):
  File "/Users/olivier.korach/venv/oko/bin/sonar-measures-export", line 8, in <module>
    sys.exit(main())
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/tools/measures_export.py", line 330, in main
    data.update(__get_json_measures_history(obj, wanted_metrics))
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/tools/measures_export.py", line 57, in __get_json_measures_history
    data["history"] = obj.get_measures_history(wanted_metrics)
AttributeError: 'Branch' object has no attribute 'get_measures_history'
```

**Comment by okorach** [comment]
Fixed
