### ISSUE TITLE
sonar-findings-export crashes when exporting findings of a PR

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1198]
```
sonar-findings-export -k okorach_sonar-tools -p 1182
/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
2024-07-17 10:38:31,811 | sonar-findings-export | INFO    | MainThread      | Set logging level to INFO
2024-07-17 10:38:31,811 | sonar-findings-export | INFO    | MainThread      | sonar-tools version 3.3
2024-07-17 10:38:31,811 | sonar-findings-export | INFO    | MainThread      | Checking latest sonar-version on pypi.org
2024-07-17 10:38:32,083 | sonar-findings-export | INFO    | MainThread      | Latest sonar-tools version is 3.2
2024-07-17 10:38:32,116 | sonar-findings-export | INFO    | MainThread      | Exporting findings for 1 projects with params {'projectKeys': ['okorach_sonar-tools'], 'csvSeparator': ',', 'threads': 8, 'compType': 'projects', 'pullRequests': ['1182'], 'useFindings': False, 'sarifNoCustomProperties': False, 'withURL': False, 'datesWithoutTime': False, 'http_timeout': 10, 'file': None, 'format': 'csv'}
key,rule,language,impacts,status,creationDate,updateDate,projectKey,projectName,branch,pullRequest,file,line,effort,message,author
2024-07-17 10:38:32,118 | sonar-findings-export | INFO    | MainThread      | Starting finding writer thread 'findingWriter'
Exception in thread findingSearch0:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/findings_export.py", line 317, in __get_component_findings
    findings_list = component.get_issues(filters=new_params)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 692, in get_issues
    branches_or_prs = self.get_branches_and_prs(filters)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 627, in get_branches_and_prs
    objects = {**objects, **pr}
TypeError: 'list' object is not a mapping
```

**Comment by okorach** [comment]
Workaround is to not specify one (or some) PR id(s) but use * instead:

```
sonar-findings-export -k <projectKey> -p '*'
```

This will however export findings of all PRs of the project, not a selection, so one must filter the issue export afterwards to get issues of particular PRs
