### ISSUE TITLE
Importing configuration fails with 3.2/3.2.1, but is working with 3.1

### ISSUE THREAD

**Issue by jbvw** [okorach/sonar-tools#1221]
After updating sonar-tools from 3.1 to 3.2/3.2.1, importing quality gates fails with the error below. When reverting sonar-tools to 3.1., it succeeds.

Python: python 3.11 from python:3.11-slim@sha256:900b13a1730f5ad67de8549c6505d433dc59d6bdede8ff7447a0dc2b9a714c3c

Sonarqube: Community Editionv9.9.6 (build 92038) from sonarqube:lts-community@sha256:a07b27af18a199a218d60a6cbd67c1c8ac7710d915522933f5edda9ec2fb728c

```
+ timeout 300s sonar-config -v DEBUG --import --what qualitygates,qualityprofiles,rules -f tmp/sonar-tools/config/sonar-config.json
2024-07-19 13:27:06,518 | sonar-config | INFO    | MainThread      | Set logging level to DEBUG
2024-07-19 13:27:06,518 | sonar-config | INFO    | MainThread      | sonar-tools version 3.2
2024-07-19 13:27:06,519 | sonar-config | DEBUG   | MainThread      | CLI arguments = {
   "dontInlineLists": false,
   "export": false,
   "exportDefaults": false,
   "file": "tmp/sonar-tools/config/sonar-config.json",
   "fullExport": false,
   "httpTimeout": 10,
   "import": true,
   "skipVersionCheck": false,
   "threads": 8,
   "token": "<TOKEN>",
   "url": "<URL>",
   "what": "qualitygates,qualityprofiles,rules"
}
2024-07-19 13:27:06,519 | sonar-config | INFO    | MainThread      | Importing configuration to <URL>
2024-07-19 13:27:06,520 | sonar-config | INFO    | MainThread      | Importing quality gates
2024-07-19 13:27:06,521 | sonar-config | DEBUG   | MainThread      | GET: <TOKEN>@<URL>/api/qualitygates/list?q=<QUALITY_GATE>
Traceback (most recent call last):
  File "/usr/local/bin/sonar-config", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/cli/config.py", line 211, in main
    __import_config(endpoint, what, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/cli/config.py", line 177, in __import_config
    qualitygates.import_config(endpoint, data)
  File "/usr/local/lib/python3.11/site-packages/sonar/qualitygates.py", line 409, in import_config
    o = QualityGate.get_object(endpoint, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonar/qualitygates.py", line 117, in get_object
    return cls.load(endpoint, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonar/qualitygates.py", line 128, in load
    o = cls(data["name"], endpoint, data=data)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonar/qualitygates.py", line 98, in __init__
    self.conditions()
  File "/usr/local/lib/python3.11/site-packages/sonar/qualitygates.py", line 201, in conditions
    data = json.loads(self.get(APIS["details"], params={"name": self.name}).text)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sonar/sqobject.py", line 64, in get
    return self.endpoint.get(api=api, params=params, exit_on_error=exit_on_error, mute=mute)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by okorach** [comment]
Thanks for reporting this @jbvw,
I could reproduce, will fix and issue a patch release 3.2.2 quickly.
