### ISSUE TITLE
sonar-config: import of projects using DevOps Platform Integrations fails!

### ISSUE THREAD

**Issue by LUMERIIX** [okorach/sonar-tools#1244]
I'm using a offline installed version sonar-tools.  
commit: fcc60988b1efe64c18e2ac3ef28f72dc34e49f6b  

reproduction scenario:  
- setup sonarqube-community:10.6 (docker)
- interactively configure global settings - DevOps Platform Integrations
- interactively configured multiple projects (some with DevOps Platform Integrations some without)
- export each configuration (for each what) `sonar-config -e -w <resource>`
- import projects.json using `sonar-config -i -w projects.json`
==> import fails at first project using DevOps Platform Integrations

log:  
```
024-08-15 16:02:53,714 | sonar-config | INFO    | MainThread      | Importing project key 'EyeSuite-Next-desktop'
2024-08-15 16:02:53,952 | sonar-config | INFO    | MainThread      | Importing project key 'HSD_HSEyeSuiteExtBiometry2Viewer_AYU0_McrLNyQ-NoF94_r'
Traceback (most recent call last):
  File "/home/lj/python3-sonar-tools-venv/bin/sonar-config", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/cli/config.py", line 215, in main
    __import_config(endpoint, what, **kwargs)
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/cli/config.py", line 191, in __import_config
    projects.import_config(endpoint, data, key_list=key_list)
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/projects.py", line 1410, in import_config
    o.update(data)
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/projects.py", line 1214, in update
    self.set_devops_binding(data["binding"])
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/projects.py", line 1098, in set_devops_binding
    if not devops.exists(alm_key, self.endpoint):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/devops.py", line 240, in exists
    return get_object(devops_platform_key, endpoint) is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/devops.py", line 230, in get_object
    return DevopsPlatform.read(endpoint, devops_platform_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/devops.py", line 76, in read
    return cls.load(endpoint, plt_type, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lj/python3-sonar-tools-venv/lib/python3.11/site-packages/sonar/devops.py", line 82, in load
    key = data["key"]
          ~~~~^^^^^^^
KeyError: 'key'
```

Thx in advance

**Comment by LUMERIIX** [comment]
@okorach

**Comment by okorach** [comment]
Hi @LUMERIIX,

Thanks for reporting this. Indeed there are a couple of residual bugs on sonar-config import.
I am working on fixing them at the moment. Stay tuned.
