### ISSUE TITLE
sonar-projects-import fails ungracefully when providing a non existing import file

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1262]
```
$ sonar-tools sonar-projects-import -f foo.csv

Traceback (most recent call last):
  File "/opt/venv/bin/sonar-projects-import", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.9/site-packages/cli/projects_import.py", line 69, in main
    with open(kwargs["projectsFile"], "r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'foo.csv'
```

**Comment by okorach** [comment]
Fixed in #1272
