### ISSUE TITLE
Quality gates import fails on SonarCloud

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1290]
```
2024-09-19 17:04:29,927 | sonar-config | INFO    | MainThread      | Importing quality gates
2024-09-19 17:04:30,377 | sonar-config | ERROR   | MainThread      | POST Error: 46***e9@https://sonarcloud.io/api/qualitygates/create_condition?gateName=BU%20Blah%20blah&metric=new_coverage&op=LT&error=10&organization=okorach HTTP status code 400 - For request URL https://sonarcloud.io/api/qualitygates/create_condition?gateName=BU+Blah+blah&metric=new_coverage&op=LT&error=10&organization=okorach
HTTP error 400 - : The 'gateId' parameter is missing
Traceback (most recent call last):
  File "/Users/olivier.korach/venv/oko/bin/sonar-config", line 8, in <module>
    sys.exit(main())
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 249, in main
    __import_config(endpoint, what, **kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 201, in __import_config
    qualitygates.import_config(endpoint, data)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/qualitygates.py", line 405, in import_config
    ok = ok and o.update(**data)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/qualitygates.py", line 287, in update
    ok = self.set_conditions(data.get("conditions", []))
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/qualitygates.py", line 241, in set_conditions
    ok = ok and self.post("qualitygates/create_condition", params=params).ok
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/sqobject.py", line 102, in post
    return self.endpoint.post(api=api, params=params, exit_on_error=exit_on_error, mute=mute)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 194, in post
    return self.__run_request(requests.post, api, params, exit_on_error, mute, **kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 247, in __run_request
    raise e
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 237, in __run_request
    r.raise_for_status()
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://sonarcloud.io/api/qualitygates/create_condition?gateName=BU+Blah+blah&metric=new_coverage&op=LT&error=10&organization=okorach
```

**Comment by okorach** [comment]
Fixed
