### ISSUE TITLE
sonar-finding-export crashes on circular import

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1355]
```
$ sonar-findings-export -b
Traceback (most recent call last):
  File "/Users/olivier.korach/venv/oko/bin/sonar-findings-export", line 5, in <module>
    from cli.findings_export import main
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/findings_export.py", line 41, in <module>
    from sonar import issues, hotspots, findings
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/issues.py", line 37, in <module>
    from sonar import users, sqobject, findings, changelog, projects
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/findings.py", line 36, in <module>
    from sonar import projects, rules
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 47, in <module>
    from sonar import pull_requests, branches
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/branches.py", line 32, in <module>
    from sonar import components, syncer, settings, exceptions
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/syncer.py", line 135, in <module>
    src_findings: list[findings.Finding], tgt_findings: list[findings.Finding], settings: types.ConfigSettings
AttributeError: partially initialized module 'sonar.findings' has no attribute 'Finding' (most likely due to a circular import)
```

**Comment by okorach** [comment]
Fixed in Release 3.4.1
