### ISSUE TITLE
Running sonar-audit: TypeError: sequence item 0: expected str instance, int found

### ISSUE THREAD

**Issue by kad-meedel** [okorach/sonar-tools#1386]
I get errors running sonar-audit within a wsl2 environment.

2024-10-07 16:49:57,752 | sonar-audit | INFO    | MainThread      | User 'admin' default password has been changed  ( last good message  )
Traceback (most recent call last):
  File "/home/xxxxxxx/.local/bin/sonar-audit", line 8, in <module>
    sys.exit(main())
  File "/home/xxxxxxx/.local/lib/python3.10/site-packages/cli/audit.py", line 167, in main
    problems = _audit_sq(sq, settings, what_to_audit=util.check_what(kwargs[options.WHAT], _ALL_AUDITABLE, "audited"), key_list=key_list)
  File "/home/xxxxxxx/.local/lib/python3.10/site-packages/cli/audit.py", line 86, in _audit_sq
    problems += sq.audit(audit_settings=settings)
  File "/home/xxxxxxx/.local/lib/python3.10/site-packages/sonar/platform.py", line 516, in audit
    + self._audit_lta_latest()
  File "/home/xxxxxxx/.local/lib/python3.10/site-packages/sonar/platform.py", line 644, in _audit_lta_latest
    return [Problem(rule, self.url, ".".join(sq_vers), ".".join(v))]
TypeError: sequence item 0: expected str instance, int found

Running on WSL2
with sonarqube 10.5.1 Developer Edition
Python3 version 3.10.12

**Comment by okorach** [comment]
Hi @kad-meedel ,

Thanks for reporting this. Can you tell me which version of `sonar-tools` you use ?

Olivier

**Comment by kad-meedel** [comment]
Hi Olivier,

Thanks for your reply.
I am using the latest!  sonar-tools version 3.4.1

Bert

**Comment by okorach** [comment]
Thanks Bert,

Problem understood. I will make a fix soon.
