### ISSUE TITLE
sonar-config -i import of groups fail with `The 'currentName' parameter is missing (POST request)` message

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#1399]
```
2024-10-13 10:15:59,657 | sonar-config | ERROR   | MainThread      | For request URL http://localhost:10020/api/user_groups/update?id=security-auditors&description=Security+Auditors+in+charge+of+reviewing+security+issues
HTTP error 400 - : The 'currentName' parameter is missing (POST request)
Traceback (most recent call last):
  File "/Users/olivier.korach/venv/oko/bin/sonar-config", line 8, in <module>
    sys.exit(main())
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 342, in main
    __import_config(endpoint, what, **kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 310, in __import_config
    func(endpoint, data, key_list=key_list)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/groups.py", line 363, in import_config
    create_or_update(endpoint, name, desc)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/groups.py", line 340, in create_or_update
    o.set_description(description)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/groups.py", line 215, in set_description
    r = self.post(_UPDATE_API, params={"id": self.key, "description": description})
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/sqobject.py", line 102, in post
    return self.endpoint.post(api=api, params=params, exit_on_error=exit_on_error, mute=mute)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 201, in post
    return self.__run_request(requests.post, api, params, exit_on_error, mute, **kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 256, in __run_request
    raise e
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/platform.py", line 249, in __run_request
    r.raise_for_status()
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: http://localhost:10020/api/user_groups/update?id=security-auditors&description=Security+Auditors+in+charge+of+reviewing+security+issues
```

**Comment by okorach** [comment]
Fixed in #1452
