### ISSUE TITLE
sonar-config import failed when setting parameter `sonar.coverage.jacoco.xmlReportPaths`

### ISSUE THREAD

**Issue by Jay-jakwak4** [okorach/sonar-tools#1442]
Hi 

I performed the command below 

sonar-config -u ${SONAR_HOST_1} -t ${SONAR_TOKEN_1} --export --what “projects” > export_projects.json

sonar-config -u ${SONAR_HOST_2} -t ${SONAR_TOKEN_2}--import --what “projects” -f export_projects.json

However, I get an error like below when I import. 

```
2024-10-23 17:18:54,976 | sonar-config | ERROR   | MainThread      | URL ${SONAR_HOST_2}/api/settings/set?key=sonar.coverage.jacoco.xmlReportPaths&component=${PROJECT}&value=build%2Freports%2Fjacoco%2FjacocoRootUnitTestReport%2FjacocoRootUnitTestReport.xml: HTTP error 400 - : Parameter 'value' must be used for single value setting. Parameter 'values' must be used for multi value setting. ( request)
```

It seems that the error occurs if a value is set in General Settings - jacoco - sonar.coverage.jacoco.xmlReportPaths for a specific project 

Thanks

**Comment by Jay-jakwak4** [comment]
sonar-tools version 3.5

**Comment by okorach** [comment]
Hi @Jay-jakwak4 ,

Thanks for reporting this. I will have a look.

**Comment by Jay-jakwak4** [comment]
@okorach 

This also throws an error 

```
sonar-config -u https://sonarqube.****.com -t **** --export > export.json
sonar-config -u https://sonarqube-secondary.****.com -t **** --import -f export.json

```

```
❯ sonar-config -u https://sonarqube-secondary.coupangdev.com -t squ_40ac1fad2f4e7f4da7bf2006b591de5d3cd9a002 --import -f export.json

2024-10-24 09:29:37,658 | sonar-config | INFO    | MainThread      | Set logging level to INFO
2024-10-24 09:29:37,658 | sonar-config | INFO    | MainThread      | sonar-tools version 3.5
2024-10-24 09:29:37,658 | sonar-config | INFO    | MainThread      | Checking latest sonar-version on pypi.org
2024-10-24 09:29:38,420 | sonar-config | INFO    | MainThread      | Latest sonar-tools released version is 3.5
2024-10-24 09:29:38,747 | sonar-config | INFO    | MainThread      | Importing configuration to https://sonarqube-secondary.****.com
2024-10-24 09:29:38,753 | sonar-config | INFO    | MainThread      | Importing groups
2024-10-24 09:29:38,753 | sonar-config | INFO    | MainThread      | Listing groups
2024-10-24 09:29:39,701 | sonar-config | INFO    | MainThread      | Loading 6 Groups...
2024-10-24 09:29:39,701 | sonar-config | INFO    | MainThread      | Importing users
2024-10-24 09:29:40,570 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:41,033 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:41,366 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:41,646 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:41,917 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:42,277 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:42,549 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:42,864 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:43,100 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:43,317 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:43,591 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:43,918 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:44,135 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:44,337 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:44,537 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:44,724 | sonar-config | INFO    | MainThread      | Loading 1 Users...
2024-10-24 09:29:44,930 | sonar-config | INFO    | MainThread      | Loading 1 Users...
Traceback (most recent call last):
  File "/Users/jakwak4/Library/Python/3.9/bin/sonar-config", line 8, in <module>
    sys.exit(main())
  File "/Users/jakwak4/Library/Python/3.9/lib/python/site-packages/cli/config.py", line 342, in main
    __import_config(endpoint, what, **kwargs)
  File "/Users/jakwak4/Library/Python/3.9/lib/python/site-packages/cli/config.py", line 310, in __import_config
    func(endpoint, data, key_list=key_list)
  File "/Users/jakwak4/Library/Python/3.9/lib/python/site-packages/sonar/users.py", line 489, in import_config
    o.update(**data)
  File "/Users/jakwak4/Library/Python/3.9/lib/python/site-packages/sonar/users.py", line 256, in update
    self.set_scm_accounts(kwargs.get("scmAccounts", None))
  File "/Users/jakwak4/Library/Python/3.9/lib/python/site-packages/sonar/users.py", line 334, in set_scm_accounts
    r = self.post(UPDATE_API, params={"login": self.login, "scmAccount": ",".join(accounts_list)})
TypeError: can only join an iterable
```

Thanks

**Comment by Jay-jakwak4** [comment]
I can see that names contain _alpha_ , _digit_ , _hyphens_(-) , _underbar_(_) , _dot_(.) , etc..

**Comment by Jay-jakwak4** [comment]
And if the error occurred on the 17th user, 
In export.json, the 17th user has “group”, “local”, and “name” in its subset 
The other user has “email”, “group”, and “name” as subset 

If you want more detailed logs, we can use a support ticket. 
Thanks

**Comment by okorach** [comment]
Hello @Jay-jakwak4,
I could reproduce the `TypeError: can only join an iterable` and opened another issue for that. See #1445 
I could also reproduce your initial problem.
```
Call stack:
  File "/Users/olivier.korach/venv/oko/bin/sonar-config", line 8, in <module>
    sys.exit(main())
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 283, in main
    __import_config(endpoint, what, **kwargs)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/cli/config.py", line 250, in __import_config
    func(endpoint, data, key_list=key_list)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 1585, in import_config
    o.update(data)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 1361, in update
    self.set_settings(settings_to_apply)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/projects.py", line 1202, in set_settings
    settings.set_setting(endpoint=self.endpoint, key=key, value=value, component=self)
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/settings.py", line 507, in set_setting
    log.error("%s while setting setting '%s'", util.error_msg(e), key, str(component))
  File "/Users/olivier.korach/venv/oko/lib/python3.9/site-packages/sonar/logging.py", line 96, in error
    __LOGGER.error(*params)
Message: "%s while setting setting '%s'"
Arguments: ("URL http://localhost:8888/api/settings/set?key=sonar.coverage.jacoco.xmlReportPaths&component=project1&value=%2A%2A%2F%2Ajacoco%2A.xml: HTTP error 400 - : Parameter 'value' must be used for single value setting. Parameter 'values' must be used for multi value setting.", 'sonar.coverage.jacoco.xmlReportPaths', "project 'project1'")
```
