### ISSUE TITLE
sonar-housekeeper not working to me

### ISSUE THREAD

**Issue by u001157** [okorach/sonar-tools#870]
Hello, 
Could you helping me with the bellow problem? I'm new using that tool.

sonar-tools % sonar-housekeeper -t 36... -u https://sonarqube.... -P 120        
2023-04-24 11:15:35,182 | sonar-tools | INFO    | MainThread      | Set debug level to INFO
2023-04-24 11:15:35,183 | sonar-tools | INFO    | MainThread      | sonar-tools version 2.6
2023-04-24 11:15:35,183 | sonar-tools | INFO    | MainThread      | Loading config file /Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sonar/audit/sonar-audit.properties
2023-04-24 11:15:35,188 | sonar-tools | INFO    | MainThread      | --- Auditing projects ---
2023-04-24 11:15:35,188 | sonar-tools | INFO    | MainThread      | Listing projects
Traceback (most recent call last):
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/bin/sonar-housekeeper", line 8, in <module>
    sys.exit(main())
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tools/housekeeper.py", line 209, in main
    problems = get_project_problems(args.projects, args.branches, args.pullrequests, args.threads, sq)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tools/housekeeper.py", line 53, in get_project_problems
    problems = projects.audit(endpoint=endpoint, audit_settings=settings)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sonar/projects/projects.py", line 1129, in audit
    plist = get_list(endpoint, key_list)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sonar/projects/projects.py", line 1084, in get_list
    return search(endpoint=endpoint)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sonar/projects/projects.py", line 1071, in search
    return sqobject.search_objects(
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/site-packages/sonar/sqobject.py", line 105, in search_objects
    data = json.loads(endpoint.get(api, params=new_params).text)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/joaomoreira/.pyenv/versions/3.9.0/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by u001157** [comment]
using DEBUG parameter, I realized 2 // on URL. Removing one, I received the message {"errors":[{"msg":"Insufficient privileges"}]}, but my token have admin rule.

 sonar-tools | DEBUG   | MainThread      | GET: 3*****@https://sonarqube...//api/projects/search?qualifiers=TRK&ps=500&p=1

**Comment by VijaySHegde** [comment]
A possible solution for someone facing the same issue i.e; son.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0):
My sonar instance URL was wrong. 
It should have been - export SONAR_HOST_URL=https://sonarqube.dev/sonar

instead of export SONAR_HOST_URL=https://sonarqube.dev/sonar/

/ (forward slash) at the end of the export line was causing issues
