### ISSUE TITLE
sonar-housekeper 400 client error for /api/project_branches/delete

### ISSUE THREAD

**Issue by jblaine** [okorach/sonar-tools#890]
sonar-tools 2.7.1 gives us the following when running sonar-housekeper against Sonarqube Enterprise 9.9.1 LTS. The variable `$T` contains a "User token" of a user that is in a group that has "Administer System" privileges.
```
sonar-housekeeper -t $T --url https://sonarqube.our.com --threads 3 --mode delete -v DEBUG 2>&1 | tee sonarqube-cleanup-20230616.log
...<deleted>...
SECURITY,MEDIUM,"token 'midas-pipeline' of user 'jimsmith' is not used since 46 days, it should be revoked"
Traceback (most recent call last):
  File "/home/jblaine/testenv/bin/sonar-housekeeper", line 8, in <module>
    sys.exit(main())
  File "/home/jblaine/testenv/lib/python3.9/site-packages/tools/housekeeper.py", line 219, in main
    (deleted_proj, deleted_loc, deleted_branches, deleted_prs, revoked_tokens) = _delete_objects(problems, mode)
  File "/home/jblaine/testenv/lib/python3.9/site-packages/tools/housekeeper.py", line 180, in _delete_objects
    elif mode != "delete" or obj.delete():
  File "/home/jblaine/testenv/lib/python3.9/site-packages/sonar/projects/branches.py", line 191, in delete
    return sq.delete_object(self, APIS["delete"], {"branch": self.name, "project": self.concerned_object.key}, _OBJECTS)
  File "/home/jblaine/testenv/lib/python3.9/site-packages/sonar/sqobject.py", line 131, in delete_object
    r = object.post(api, params=params, mute=(HTTPStatus.NOT_FOUND,))
  File "/home/jblaine/testenv/lib/python3.9/site-packages/sonar/sqobject.py", line 77, in post
    return self.endpoint.post(api=api, params=params, exit_on_error=exit_on_error, mute=mute)
  File "/home/jblaine/testenv/lib/python3.9/site-packages/sonar/platform.py", line 196, in post
    r.raise_for_status()
  File "/home/jblaine/testenv/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error:  for url: https://sonarqube.our.com/api/project_branches/delete
```

**Comment by okorach** [comment]
Thanks for the notice @jblaine.

1. I need to look at what HTTP request is generated to delete the branch to understand what is going on.
In DEBUG logs the complete HTTP request is normally displayed in stdout, but this is not the case in your log.
Could it be that it's only in the `sonarqube-cleanup-20230616.log` that you tee into ?
Once the HTTP request is found, I would need to you run it isolated from the command line to check if that is a bug in sonar-housekeeper or a change of behavior of the `api/project_branches/delete` between 8.9 and 9.9 (Changes of API are quite frequent with SonarQube...)

I would need to confirm that the HTTP request should look like:

`POST https://sonarqube.our.com/api/project_branches/delete?branch=<branchName>&project=<projectKey>`

2. If you have access to the command line on your SonarQube server that would help if you could collect the logs on the SonarQube side at the moment you execute `sonar-housekeeper` (precisely when you run the branch deleting API command). In particular that would help if I could get (in the short time window when the problem happens):
- What is the output in `access.log`. You should find the corresponding HTTP requests from User Agent (UA) sonar-tools
- What is the output in `web.log`. You should see some sort of error as the root cause of the HTTP 400 response

PS: Please run all your tests of `sonar-housekeeper commands ` temporarily with `--threads 1` until everything works fine. Activating multithreading makes troubleshooting of problems more tricky.

Thanks, Olivier

**Comment by okorach** [comment]
I am now also paying attention to your statement:

> The variable $T contains a "User token" of a user that is in a group that has "Administer System" privileges.

This may sound odd but permission is not sufficient. You must also verify that the group has "Administer" permission on the projects for which you want to delete branches. That may seem odd but having "Administer System" permission does not automatically grant "Administer" on all projects. 
Can you verify that ? (Navigate to the project, then  menu **Project Settings --> Permissions** and verify the "Administer" checkbox for your group)

Thanks

**Comment by jblaine** [comment]
Hi Olivier, I do have full per-project permissions assigned for this user on every project. I modified the code for more debugging and the error I am getting is:

```
POST Error: <blah>.../api/project_branches/delete?branch=master&project=che-jupyter-35693 HTTP status code 400
```
The requests response object for that POST had this message accessible via `r.iter_content(chunk_size=None)`:
`Only non-main branches can be deleted`

I looked around the project and it had no source code and was never used, so I just deleted it via the web UI. I don't know if you want to handle this differently than a 400 exception in the future.

**Comment by jblaine** [comment]
And now I'm hitting a new problem, with 1 thread being used per your recommendation when debugging. I've removed unnecessary content from the front of each log line to shorten them:
```
POST: squ_f8***fd@https://sonarqube.our.com/api/project_branches/delete?branch=additional-tags&project=custom-job-test-43316
Successfully deleted branch 'additional-tags' of project 'custom-job-test-43316'
Deleting branch 'additional-tags' of project 'custom-job-test-43316'
Deleting branch 'additional-tags' of project 'custom-job-test-43316'
POST: squ_f8***fd@https://sonarqube.our.com/api/project_branches/delete?branch=additional-tags&project=custom-job-test-43316
JBLAINE_response_iter_content = b'{"errors":[{"msg":"Branch \\u0027additional-tags\\u0027 not found for project \\u0027custom-job-test-43316\\u0027"}]}'
POST Error: squ_f8***fd@https://sonarqube.our.com/api/project_branches/delete?branch=additional-tags&project=custom-job-test-43316 HTTP status code 404
```

**Comment by okorach** [comment]
Thanks for all this @jblaine ,
Now I understand the problem.
- sonar-housekeeper tries to delete main branches which is forbidden (it's quite rare that there is no activity on the main branch causing it to be candidate for deletion by sonar-housekeeper
- When deleting a branch, sonar-housekeeper apparently tries to delete twice, which causes the 2nd deletion to fail...

I'll fix that soon.
