### ISSUE TITLE
sonar-issues-sync  fails with AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by yossile77** [okorach/sonar-tools#911]
-- my sonarqube version is 8.9.6
-- 
sonar-issues-sync -k xxx  -K yyy   --login admin
2023-11-02 10:23:05,641 | sonar-tools | INFO    | MainThread      | Set debug level to INFO
Traceback (most recent call last):
  File "./sonar-issues-sync", line 11, in <module>
    sys.exit(main())
  File "/sonarhome/inf/sonar/.local/lib/python3.6/site-packages/tools/findings_sync.py", line 142, in main
    src_branch = Branch.get_object(projects.Project.get_object(source_key, source_env), source_branch)
  File "/sonarhome/inf/sonar/.local/lib/python3.6/site-packages/sonar/projects/projects.py", line 85, in get_object
    data = json.loads(endpoint.get(_SEARCH_API, params={"projects": key}).text)
AttributeError: 'str' object has no attribute 'get'

**Comment by okorach** [comment]
Hello @yossile77,

Thanks for reporting this.
Maybe I ask you to rerun the same command in DEBUG and send me the full log. You may redact the project keys if you want to keep them confidential.
That should be part of the debug logs but I need to know which version of sonar-tools you use.

**Comment by yossile77** [comment]
H Olivier,

i've tried latest 2.7.1 and also 2.7 2.6 all will give same error -

from the installation of sonar-tools -

Uninstalling sonar-tools-2.6:
      Successfully uninstalled sonar-tools-2.6
Successfully installed sonar-tools-2.7.1

The command -

./sonar-issues-sync -k XXX -K YYY --login admin -v DEBUG

cat sonar-tools.log
2023-11-07 14:22:54,219 | sonar-tools | INFO    | MainThread      | Set
debug level to DEBUG
2023-11-07 14:22:54,219 | sonar-tools | DEBUG   | MainThread      | GET:
***@***.***://moncclin16:9000/api/projects/search?projects=XXX
2023-11-07 14:22:54,596 | sonar-tools | DEBUG   | MainThread      | Created
object project 'XXX'
2023-11-07 14:22:54,601 | sonar-tools | DEBUG   | MainThread      | GET:
***@***.***://moncclin16:9000/api/projects/search?projects=YYY
2023-11-07 14:22:54,929 | sonar-tools | DEBUG   | MainThread      | Created
object project 'YYY'

This is all in log I can see -

**Comment by yossile77** [comment]
and this is what I have from the console -


Traceback (most recent call last):
  File "./sonar-issues-sync", line 11, in <module>
    sys.exit(main())
  File
"/sonarhome/inf/sonar/.local/lib/python3.6/site-packages/tools/findings_sync.py",
line 142, in main
    src_branch = Branch.get_object(projects.Project.get_object(source_key,
source_env), source_branch)
  File
"/sonarhome/inf/sonar/.local/lib/python3.6/site-packages/sonar/projects/projects.py",
line 85, in get_object
    data = json.loads(endpoint.get(_SEARCH_API, params={"projects":
key}).text)
AttributeError: 'str' object has no attribute 'get'


Somehow it fails when trying get the branch.

Maybe didn't mention I am using sonarqube community edition + sonar
community plugin

[image: image.png]
.

**Comment by okorach** [comment]
Thanks. I will look into it.
I hope to release a new version soon that will fix the problem.
