### ISSUE TITLE
Full import of a partial configuration export crashes the import

### ISSUE THREAD

**Issue by okorach** [okorach/sonar-tools#940]
Because the full import process expects all data elements in the JSON and the partial export has only produced partial elements data in the JSON

**Comment by okorach** [comment]
Example reproducer:
```
# Export only quality gates
sonar-config -e -f conf.json -w qualitygates -t <token> -u <url>
2024-02-24 12:21:02,926 | sonar-tools | INFO    | MainThread      | Set debug level to INFO
2024-02-24 12:21:02,926 | sonar-tools | INFO    | MainThread      | sonar-tools version 2.8.2
2024-02-24 12:21:02,934 | sonar-tools | INFO    | MainThread      | Exporting configuration from http://localhost:9999
2024-02-24 12:21:03,264 | sonar-tools | INFO    | MainThread      | Exporting quality gates
2024-02-24 12:21:03,265 | sonar-tools | INFO    | MainThread      | Getting quality gates
2024-02-24 12:21:03,330 | sonar-tools | INFO    | MainThread      | Exporting configuration from http://localhost:9999 completed
2024-02-24 12:21:03,330 | sonar-tools | INFO    | MainThread      | Total execution time: 0:00:00.396933

# Import just exported config file (that contains only QG), without specifying any -w
$ sonar-config -i -f conf.json -t <token> -u <url>
2024-02-24 12:21:06,089 | sonar-tools | INFO    | MainThread      | Set debug level to INFO
2024-02-24 12:21:06,089 | sonar-tools | INFO    | MainThread      | sonar-tools version 2.8.2
2024-02-24 12:21:06,090 | sonar-tools | INFO    | MainThread      | Importing configuration to http://localhost:9999
2024-02-24 12:21:06,090 | sonar-tools | INFO    | MainThread      | No groups groups to import
2024-02-24 12:21:06,090 | sonar-tools | INFO    | MainThread      | No users to import
2024-02-24 12:21:06,090 | sonar-tools | INFO    | MainThread      | Importing quality gates
2024-02-24 12:21:06,248 | sonar-tools | INFO    | MainThread      | Getting quality gates
2024-02-24 12:21:06,301 | sonar-tools | INFO    | MainThread      | No customized rules (custom tags, extended description) to import
2024-02-24 12:21:06,301 | sonar-tools | INFO    | MainThread      | No quality profiles to import
Traceback (most recent call last):
  File "/home/olivier/sonar-tools/.venv/bin/sonar-config", line 8, in <module>
    sys.exit(main())
  File "/home/olivier/sonar-tools/.venv/lib/python3.10/site-packages/tools/config.py", line 191, in main
    __import_config(endpoint, what, args)
  File "/home/olivier/sonar-tools/.venv/lib/python3.10/site-packages/tools/config.py", line 166, in __import_config
    endpoint.import_config(data["globalSettings"])
KeyError: 'globalSettings'
```
